/***************************************************************************
 * This source file is part of the RemoteBees open source project.         *
 *                                                                         *
 * Licensed under the MIT License. See LICENSE for license information     *
 ***************************************************************************/

@startuml

title JobBoard

[*] --> Main

Main --> Login
Main --> Profile
Main --> Search
Main --> ViewDetail

Login --> Main
Profile --> Main
Search --> Main
ViewDetail --> Main

ViewDetail: JobItem
Search: String

!$export_lang = %getenv("export_lang")
!if ($export_lang == "swift")
Main --> [*]
Main: Promise<[JobItem]>
!else
Main --> [*]: Int
Main: AsyncJobItems
!endif

@enduml
