@startuml

title JobBoard

[*] --> Main

Main --> Login
Main --> Profile
Main --> Search
Main --> ViewDetail

Login --> Main
Profile --> Main
Search --> Main
ViewDetail --> Main

Main --> [*]

ViewDetail: JobItem
Search: String

!$export_lang = %getenv("export_lang")
!if ($export_lang == "swift")
Main: Promise<[JobItem]>
!else
Main: AsyncJobItems
!endif

@enduml
