@startuml

title Login

!$export_lang = %getenv("export_lang")

[*] --> Prompt

Prompt --> ForgotPassword
Prompt --> SubmitLogin

ForgotPassword --> SubmitForgotPassword

SubmitForgotPassword --> ForgotPassword
SubmitForgotPassword --> Prompt

ForgotPassword --> Prompt
SubmitLogin --> Prompt

SubmitLogin: LoginContext
SubmitForgotPassword: String

' Temporary workaround for a FlowKit bug in Android where
' a flow returns Void/Unit would cause NullPointerException
!if ($export_lang == "swift")
SubmitLogin --> [*]
!else
SubmitLogin --> [*]: Int
!endif

@enduml
