@startuml

title Login

[*] --> Prompt

Prompt --> ForgotPassword
Prompt --> SubmitLogin

ForgotPassword --> SubmitForgotPassword

SubmitForgotPassword --> ForgotPassword
SubmitForgotPassword --> Prompt

ForgotPassword --> Prompt
SubmitLogin --> Prompt

Prompt --> [*]
SubmitLogin --> [*]

@enduml
