@startuml

title Onboard

[*] --> Prompt

Prompt --> Login
Prompt --> SignUp
Prompt --> Skip

Login --> JobBoard
Login --> Prompt

SignUp --> JobBoard
SignUp --> Prompt

Skip --> JobBoard

JobBoard --> [*]
Prompt --> [*]

@enduml
