@startuml

title Onboard

!$export_lang = %getenv("export_lang")

[*] --> Prompt

Prompt --> Login
Prompt --> SignUp
Prompt --> Skip

Login --> Prompt
SignUp --> Prompt

' Temporary workaround for a FlowKit bug in Android where
' a flow returns Void/Unit would cause NullPointerException
!if ($export_lang == "swift")
Login --> [*]
SignUp --> [*]
Skip --> [*]
!else
Login --> [*]: Int
SignUp --> [*]: Int
Skip --> [*]: Int
!endif

@enduml
