/***************************************************************************
 * This source file is part of the RemoteBees open source project.         *
 *                                                                         *
 * Licensed under the MIT License. See LICENSE for license information     *
 ***************************************************************************/

@startuml

title SignUp

!$export_lang = %getenv("export_lang")

[*] --> Prompt

Prompt --> SubmitSignUp

SubmitSignUp --> Prompt
SubmitSignUp: SignUpContext

' Temporary workaround for a FlowKit bug in Android where
' a flow returns Void/Unit would cause NullPointerException
!if ($export_lang == "swift")
SubmitSignUp --> [*]
!else
SubmitSignUp --> [*]: Int
!endif

@enduml
