/***************************************************************************
 * This source file is part of the RemoteBees open source project.         *
 *                                                                         *
 * Licensed under the MIT License. See LICENSE for license information     *
 ***************************************************************************/

@startuml Startup

title Startup
note "Startup flow is the application entry flow " as N1

!$export_lang = %getenv("export_lang")

[*] --> Entry

Entry --> Onboard
Entry --> JobBoard

Onboard --> JobBoard

' Temporary workaround for a FlowKit bug in Android where
' a flow returns Void/Unit would cause NullPointerException
!if ($export_lang == "swift")
JobBoard --> [*]
!else
JobBoard --> [*]: Int
!endif

@enduml
